### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
For [your RFP with F-Droid](https://gitlab.com/fdroid/rfp/-/issues/1563). To build on this, be welcome using my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688). It would e.g. be a very good idea to move the screenshots in:

* `pics/Android_Feature_Graphic.png` => `.../en-US/images/featureGraphic.png`
* `pics/ClementineRemote_(Files|Library|Playlist|Radio|v0.1).png` => `.../en-US/images/phoneScreenshots/`

I didn't include that with this PR as I didn't want to break any links you might have to the current locations.

Once this is merged and you've added/moved what you wanted into Fastlane, please let me know if you want me to cross-check. It then needs to be tagged so F-Droid can pick it up (my repo updater could pick it up immediately, but I need to enable that first for your app – so catching two birds with a single grain :smile:)

### CODE REVIEW

**Comment by mbruel** [comment]
cool thanks, I'll have a look tomorrow or the day after.
Is FDroid able to build Qt apps now? or do I still have to provide the apk?
If you managed to build, I'm interested to know how as I'd like to do it also automatically for another project.
Keep in touch ;)

**Comment by IzzySoft** [comment]
> I'll have a look tomorrow or the day after.

Great, thanks!

> Is FDroid able to build Qt apps now?

I'm not sure – we'll find out, right? IMHO we have a few simple ones, but I can't put my finger on it right now.

> or do I still have to provide the apk?

Please do, at least until it shows up at "F-Droid proper". Once that happens, please let me know if you want to continue providing the APK or, as I usually do, I should "unlist" your app from my repo then.

> If you managed to build

We're not that far yet, we're still at RFP. I've used your request today for a "training course" to get potential new contributors started – was a good example :smile: Once the RFP is on "ready" we can try a merge request at fdroiddata if you want – we'd prepare the basic YAML metadata file, and you could use that to open a MR. Then we see if it works, and hopefully you'll be able to make some adjustments to the build recipe when needed. I'm still a very junior when it comes to packaging…

**Comment by mbruel** [comment]
wow too many acronyms for me...
what's FRP and MR? (I found IMHO on google ;))

I'm going to fill the english and french files. I'll let you know when it is done.
Yep, I'm interesed to build the YAML file with your help. Would be great if you could find some examples of Qt apps compiled for Android.

Cheers

**Comment by mbruel** [comment]
what is the format of full_description.txt?
is it pure html, Markdown, BB code?

**Comment by IzzySoft** [comment]
> what's FRP and MR?

No idea what FRP is – oh wait: Factory Reset Protection :speak_no_evil: RFP = Request For Packaging. MR = Merge Request – the GitLab equivalent to Pull Requests.

> I'm going to fill the english and french files. I'll let you know when it is done.

Great! Looking forward to that.

> Yep, I'm interesed to build the YAML file with your help. Would be great if you could find some examples of Qt apps compiled for Android.

Thanks! And oops. As I wrote, I'm a "freshman" when it comes to packaging – I can do the easy ones if all our pipelines yield green. We could turn up some examples, possibly, when checking the [closed RFPs with qt label](https://gitlab.com/fdroid/rfp/-/issues?scope=all&utf8=%E2%9C%93&state=closed&label_name[]=qt). Hm, only 5 of them. Metronom [I've merged](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7873), the bot succeeded building – so you can even cross-check with that MR.

> what is the format of full_description.txt?

Plain text basically, with some HTML options. Which ones exactly, and how it's interpreted, differs from the place of distribution. I've written something up [here in my Wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) which could serve as a guide. Best compromise is possibly what I call "Markdown lite" :laughing:

**Pull request merged**
